/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ipaymentSol from "./Ipayment.sol";
export type { ipaymentSol };
export type { ImQuark } from "./ImQuark";
