/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ipaymentSol from "./Ipayment.sol";
export type { ipaymentSol };
import type * as paymentSol from "./payment.sol";
export type { paymentSol };
export type { ImQuarkNFT } from "./ImQuarkNFT";
