/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IImportedContractsInterface extends utils.Interface {
  functions: {
    "resetSlotToDefault(address,address,uint256,uint256,string)": FunctionFragment;
    "subscribeToEntities(address,address,uint256,uint256[],string[])": FunctionFragment;
    "subscribeToEntity(address,address,uint256,uint256,string)": FunctionFragment;
    "tokenEntityURI(address,uint256,uint256)": FunctionFragment;
    "transferTokenEntityURI(address,address,uint256,uint256,string)": FunctionFragment;
    "updateURISlot(address,address,uint256,uint256,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "resetSlotToDefault"
      | "subscribeToEntities"
      | "subscribeToEntity"
      | "tokenEntityURI"
      | "transferTokenEntityURI"
      | "updateURISlot"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "resetSlotToDefault",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeToEntities",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeToEntity",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenEntityURI",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokenEntityURI",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateURISlot",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "resetSlotToDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeToEntities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeToEntity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenEntityURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokenEntityURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateURISlot",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IImportedContracts extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IImportedContractsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    resetSlotToDefault(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      defaultUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subscribeToEntities(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityIds: PromiseOrValue<BigNumberish>[],
      entitySlotDefaultUris: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subscribeToEntity(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      entitySlotDefaultUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tokenEntityURI(
      _contract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferTokenEntityURI(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      soldUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateURISlot(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      entityId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      updatedUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  resetSlotToDefault(
    _contract: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    entityId: PromiseOrValue<BigNumberish>,
    defaultUri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subscribeToEntities(
    _contract: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    entityIds: PromiseOrValue<BigNumberish>[],
    entitySlotDefaultUris: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subscribeToEntity(
    _contract: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    entityId: PromiseOrValue<BigNumberish>,
    entitySlotDefaultUri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tokenEntityURI(
    _contract: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    entityId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  transferTokenEntityURI(
    _contract: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    entityId: PromiseOrValue<BigNumberish>,
    soldUri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateURISlot(
    _contract: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    entityId: PromiseOrValue<BigNumberish>,
    tokenId: PromiseOrValue<BigNumberish>,
    updatedUri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    resetSlotToDefault(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      defaultUri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    subscribeToEntities(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityIds: PromiseOrValue<BigNumberish>[],
      entitySlotDefaultUris: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    subscribeToEntity(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      entitySlotDefaultUri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenEntityURI(
      _contract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    transferTokenEntityURI(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      soldUri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateURISlot(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      entityId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      updatedUri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    resetSlotToDefault(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      defaultUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subscribeToEntities(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityIds: PromiseOrValue<BigNumberish>[],
      entitySlotDefaultUris: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subscribeToEntity(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      entitySlotDefaultUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tokenEntityURI(
      _contract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferTokenEntityURI(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      soldUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateURISlot(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      entityId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      updatedUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    resetSlotToDefault(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      defaultUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subscribeToEntities(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityIds: PromiseOrValue<BigNumberish>[],
      entitySlotDefaultUris: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subscribeToEntity(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      entitySlotDefaultUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tokenEntityURI(
      _contract: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferTokenEntityURI(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      entityId: PromiseOrValue<BigNumberish>,
      soldUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateURISlot(
      _contract: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      entityId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      updatedUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
