/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as solmateNftSol from "./SolmateNFT.sol";
export type { solmateNftSol };
import type * as noDelegateCallSol from "./noDelegateCall.sol";
export type { noDelegateCallSol };
