/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace ImQuarkEntity {
  export type CollectionParamsStruct = {
    templateId: PromiseOrValue<BigNumberish>;
    collectionURIs: PromiseOrValue<string>[];
    totalSupply: PromiseOrValue<BigNumberish>;
    mintPrice: PromiseOrValue<BigNumberish>;
    mintPerAccountLimit: PromiseOrValue<BigNumberish>;
    name: PromiseOrValue<string>;
    symbol: PromiseOrValue<string>;
    verifier: PromiseOrValue<string>;
    isWhitelisted: PromiseOrValue<boolean>;
  };

  export type CollectionParamsStructOutput = [
    BigNumber,
    string[],
    BigNumber,
    BigNumber,
    number,
    string,
    string,
    string,
    boolean
  ] & {
    templateId: BigNumber;
    collectionURIs: string[];
    totalSupply: BigNumber;
    mintPrice: BigNumber;
    mintPerAccountLimit: number;
    name: string;
    symbol: string;
    verifier: string;
    isWhitelisted: boolean;
  };
}

export interface MQuarkEntityInterface extends utils.Interface {
  functions: {
    "addNewCollection(address)": FunctionFragment;
    "collectFunds(uint64[])": FunctionFragment;
    "createCollection((uint256,string[],uint256,uint256,uint8,string,string,address,bool),bool,uint8,bytes32)": FunctionFragment;
    "getBalance()": FunctionFragment;
    "getCollectionAddress(uint64)": FunctionFragment;
    "getEntityInfo()": FunctionFragment;
    "getLastCollectionId()": FunctionFragment;
    "importExternalCollection(uint256,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "s_ID()": FunctionFragment;
    "s_registry()": FunctionFragment;
    "s_subscriber()": FunctionFragment;
    "transferCollection(address,uint64)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferOwnershipOfCollection(address,uint64)": FunctionFragment;
    "withdraw()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addNewCollection"
      | "collectFunds"
      | "createCollection"
      | "getBalance"
      | "getCollectionAddress"
      | "getEntityInfo"
      | "getLastCollectionId"
      | "importExternalCollection"
      | "owner"
      | "renounceOwnership"
      | "s_ID"
      | "s_registry"
      | "s_subscriber"
      | "transferCollection"
      | "transferOwnership"
      | "transferOwnershipOfCollection"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addNewCollection",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFunds",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createCollection",
    values: [
      ImQuarkEntity.CollectionParamsStruct,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntityInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastCollectionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "importExternalCollection",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "s_ID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "s_registry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_subscriber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferCollection",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnershipOfCollection",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addNewCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntityInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastCollectionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "importExternalCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_ID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "s_registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_subscriber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnershipOfCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "CollectionCreated(address,address,address,uint256,uint64,uint256,uint256,uint256,uint256,uint256,string[],uint8,bool,bool,bool)": EventFragment;
    "ExternalCollectionCreated(address,uint256,uint256,uint64)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CollectionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExternalCollectionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface CollectionCreatedEventObject {
  instanceAddress: string;
  verifier: string;
  controller: string;
  entityId: BigNumber;
  collectionId: BigNumber;
  templateId: BigNumber;
  mintPrice: BigNumber;
  totalSupply: BigNumber;
  mintLimitPerWallet: BigNumber;
  royalty: BigNumber;
  collectionURIs: string[];
  mintType: number;
  dynamic: boolean;
  free: boolean;
  whiteListed: boolean;
}
export type CollectionCreatedEvent = TypedEvent<
  [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string[],
    number,
    boolean,
    boolean,
    boolean
  ],
  CollectionCreatedEventObject
>;

export type CollectionCreatedEventFilter =
  TypedEventFilter<CollectionCreatedEvent>;

export interface ExternalCollectionCreatedEventObject {
  collectionAddress: string;
  entityId: BigNumber;
  templateId: BigNumber;
  collectionId: BigNumber;
}
export type ExternalCollectionCreatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  ExternalCollectionCreatedEventObject
>;

export type ExternalCollectionCreatedEventFilter =
  TypedEventFilter<ExternalCollectionCreatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface MQuarkEntity extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MQuarkEntityInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addNewCollection(
      _collectionAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectFunds(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createCollection(
      _collectionParams: ImQuarkEntity.CollectionParamsStruct,
      _isDynamicUri: PromiseOrValue<boolean>,
      _ERCimplementation: PromiseOrValue<BigNumberish>,
      _merkelRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCollectionAddress(
      collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getEntityInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string, string, string, string] & {
        contractAddress: string;
        creator: string;
        id: BigNumber;
        name: string;
        description: string;
        thumbnail: string;
        entitySlotDefaultURI: string;
      }
    >;

    getLastCollectionId(overrides?: CallOverrides): Promise<[BigNumber]>;

    importExternalCollection(
      _templateId: PromiseOrValue<BigNumberish>,
      _collectionAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    s_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    s_registry(overrides?: CallOverrides): Promise<[string]>;

    s_subscriber(overrides?: CallOverrides): Promise<[string]>;

    transferCollection(
      _entity: PromiseOrValue<string>,
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnershipOfCollection(
      _newOwner: PromiseOrValue<string>,
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addNewCollection(
    _collectionAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectFunds(
    _ids: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createCollection(
    _collectionParams: ImQuarkEntity.CollectionParamsStruct,
    _isDynamicUri: PromiseOrValue<boolean>,
    _ERCimplementation: PromiseOrValue<BigNumberish>,
    _merkelRoot: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getBalance(overrides?: CallOverrides): Promise<BigNumber>;

  getCollectionAddress(
    collectionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getEntityInfo(
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, string, string, string, string] & {
      contractAddress: string;
      creator: string;
      id: BigNumber;
      name: string;
      description: string;
      thumbnail: string;
      entitySlotDefaultURI: string;
    }
  >;

  getLastCollectionId(overrides?: CallOverrides): Promise<BigNumber>;

  importExternalCollection(
    _templateId: PromiseOrValue<BigNumberish>,
    _collectionAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  s_ID(overrides?: CallOverrides): Promise<BigNumber>;

  s_registry(overrides?: CallOverrides): Promise<string>;

  s_subscriber(overrides?: CallOverrides): Promise<string>;

  transferCollection(
    _entity: PromiseOrValue<string>,
    _collectionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnershipOfCollection(
    _newOwner: PromiseOrValue<string>,
    _collectionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addNewCollection(
      _collectionAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectFunds(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    createCollection(
      _collectionParams: ImQuarkEntity.CollectionParamsStruct,
      _isDynamicUri: PromiseOrValue<boolean>,
      _ERCimplementation: PromiseOrValue<BigNumberish>,
      _merkelRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectionAddress(
      collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getEntityInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string, string, string, string] & {
        contractAddress: string;
        creator: string;
        id: BigNumber;
        name: string;
        description: string;
        thumbnail: string;
        entitySlotDefaultURI: string;
      }
    >;

    getLastCollectionId(overrides?: CallOverrides): Promise<BigNumber>;

    importExternalCollection(
      _templateId: PromiseOrValue<BigNumberish>,
      _collectionAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    s_ID(overrides?: CallOverrides): Promise<BigNumber>;

    s_registry(overrides?: CallOverrides): Promise<string>;

    s_subscriber(overrides?: CallOverrides): Promise<string>;

    transferCollection(
      _entity: PromiseOrValue<string>,
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnershipOfCollection(
      _newOwner: PromiseOrValue<string>,
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "CollectionCreated(address,address,address,uint256,uint64,uint256,uint256,uint256,uint256,uint256,string[],uint8,bool,bool,bool)"(
      instanceAddress?: null,
      verifier?: null,
      controller?: null,
      entityId?: null,
      collectionId?: null,
      templateId?: null,
      mintPrice?: null,
      totalSupply?: null,
      mintLimitPerWallet?: null,
      royalty?: null,
      collectionURIs?: null,
      mintType?: null,
      dynamic?: null,
      free?: null,
      whiteListed?: null
    ): CollectionCreatedEventFilter;
    CollectionCreated(
      instanceAddress?: null,
      verifier?: null,
      controller?: null,
      entityId?: null,
      collectionId?: null,
      templateId?: null,
      mintPrice?: null,
      totalSupply?: null,
      mintLimitPerWallet?: null,
      royalty?: null,
      collectionURIs?: null,
      mintType?: null,
      dynamic?: null,
      free?: null,
      whiteListed?: null
    ): CollectionCreatedEventFilter;

    "ExternalCollectionCreated(address,uint256,uint256,uint64)"(
      collectionAddress?: null,
      entityId?: null,
      templateId?: null,
      collectionId?: null
    ): ExternalCollectionCreatedEventFilter;
    ExternalCollectionCreated(
      collectionAddress?: null,
      entityId?: null,
      templateId?: null,
      collectionId?: null
    ): ExternalCollectionCreatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    addNewCollection(
      _collectionAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectFunds(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createCollection(
      _collectionParams: ImQuarkEntity.CollectionParamsStruct,
      _isDynamicUri: PromiseOrValue<boolean>,
      _ERCimplementation: PromiseOrValue<BigNumberish>,
      _merkelRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectionAddress(
      collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntityInfo(overrides?: CallOverrides): Promise<BigNumber>;

    getLastCollectionId(overrides?: CallOverrides): Promise<BigNumber>;

    importExternalCollection(
      _templateId: PromiseOrValue<BigNumberish>,
      _collectionAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    s_ID(overrides?: CallOverrides): Promise<BigNumber>;

    s_registry(overrides?: CallOverrides): Promise<BigNumber>;

    s_subscriber(overrides?: CallOverrides): Promise<BigNumber>;

    transferCollection(
      _entity: PromiseOrValue<string>,
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnershipOfCollection(
      _newOwner: PromiseOrValue<string>,
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addNewCollection(
      _collectionAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectFunds(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createCollection(
      _collectionParams: ImQuarkEntity.CollectionParamsStruct,
      _isDynamicUri: PromiseOrValue<boolean>,
      _ERCimplementation: PromiseOrValue<BigNumberish>,
      _merkelRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCollectionAddress(
      collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntityInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLastCollectionId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    importExternalCollection(
      _templateId: PromiseOrValue<BigNumberish>,
      _collectionAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    s_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    s_registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    s_subscriber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferCollection(
      _entity: PromiseOrValue<string>,
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnershipOfCollection(
      _newOwner: PromiseOrValue<string>,
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
